myboot.name= Prod Env


#log level
logging.level.com.basic.myspringboot =info


//mariadb db info
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/boot_db
spring.datasource.username=boot
spring.datasource.password=boot
spring.datasource.driverClassName=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
#\uB108\uAC00 \uC9C0\uAE08 \uC811\uC18D\uD558\uACE0\uC788\uB294 db\uC5B8\uC5B4
#
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#N+1\uBB38\uC81C \uD574\uACB0\uC744 \uC704\uD55C \uBD88\uB7EC\uC624\uB294 \uC5F0\uAD00\uB41C \uAC1D\uCCB4 \uAC1C\uC218 \uC124\uC815\uD558\uAE30
spring.jpa.properties.hibernate.default_batch_fetch_size=100
